name: Protocol Buffer Go Stubs Generation
on:
  push:
    tags:
      - v**

permissions:
  contents: write

jobs:
  protoc:
    name: Generate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [order] # payment, shipping
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0

      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Generate for Golang
        shell: bash
        env:
          GIT_EMAIL: m.usmannadeem3344@gmail.com
          GIT_USERNAME: Muhammad Usman
        run: |
          chmod +x "${GITHUB_WORKSPACE}/protoc.sh"
          ./protoc.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }}